SCHEMA_VERSION = 2
SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at_utc TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS subscriptions (id TEXT PRIMARY KEY, owner_telegram_id INTEGER NOT NULL, name TEXT NOT NULL CHECK(length(name) BETWEEN 1 AND 160), category TEXT NOT NULL CHECK(category IN ('AI','SERVER','OTHER')), status TEXT NOT NULL CHECK(status IN ('active','inactive')), end_at_utc TEXT NOT NULL, recurrence_value INTEGER, recurrence_unit TEXT CHECK(recurrence_unit IN ('DAYS','MONTHS','YEARS','NONE')), cost_minor INTEGER, currency TEXT, service_url TEXT, note TEXT, secret_ciphertext BLOB, secret_nonce BLOB, encryption_key_version INTEGER, term_version INTEGER NOT NULL DEFAULT 1, record_version INTEGER NOT NULL DEFAULT 1, replaced_from_id TEXT REFERENCES subscriptions(id), deactivation_reason TEXT, created_at_utc TEXT NOT NULL, updated_at_utc TEXT NOT NULL, deactivated_at_utc TEXT);
CREATE TABLE IF NOT EXISTS reminder_deliveries (id TEXT PRIMARY KEY, subscription_id TEXT NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE, term_version INTEGER NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('BEFORE_48H','BEFORE_24H')), scheduled_at_utc TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('pending','claimed','sent','retryable','unknown','cancelled','failed')), attempt_count INTEGER NOT NULL DEFAULT 0, claimed_until_utc TEXT, sent_at_utc TEXT, telegram_message_id INTEGER, last_error_code TEXT, created_at_utc TEXT NOT NULL, updated_at_utc TEXT NOT NULL, UNIQUE(subscription_id,term_version,kind));
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at_utc TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS scheduler_lease (name TEXT PRIMARY KEY, holder_id TEXT, expires_at_utc TEXT, heartbeat_at_utc TEXT);
CREATE TABLE IF NOT EXISTS dialog_sessions (owner_telegram_id INTEGER PRIMARY KEY, flow_name TEXT NOT NULL, current_step TEXT NOT NULL, non_secret_payload TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY, subscription_id TEXT, event TEXT NOT NULL, created_at_utc TEXT NOT NULL, metadata_json TEXT NOT NULL DEFAULT '{}');
"""
